version: '3.8'
services:
  fastapi:
    restart: always
    build:
       context: ./backend
       dockerfile: Dockerfile
    container_name: 'fastapi'
    working_dir: '/root'
    volumes:
      - ${BACKEND_PATH}:/root/app
    env_file:
      - .env
    ports: 
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15.1
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata: